### ISSUE TITLE
Can I upgrade to Laravel 7 or Latest 6 version

### ISSUE THREAD

**Issue by kenytux** [creativetimofficial/ct-paper-dashboard-pro-laravel#1]
Hello,

Does the template support the last version 6 or 7?

**Comment by teamupdivision** [comment]
Hello, we'll follow up with an update for Laravel 7 in the next days

**Comment by teamupdivision** [comment]
Hello, we have updated to the latest Laravel version.

Thank you for using Creative Tim products!

**Comment by kenytux** [comment]
Hello
I have book Paper Dashboard Pro, but from the download page on my Creative Tim Dashboard, I find only version 1.0.1. This last one is only compatible with Laravel 6.

**Comment by teamupdivision** [comment]
Hello, did you re-download the product? Please do

**Comment by kenytux** [comment]
Yes is done. Thank You!
