### ISSUE TITLE
Version 8

### ISSUE THREAD

**Issue by kenytux** [creativetimofficial/ct-paper-dashboard-pro-laravel#2]
Hello,

Does the template support the last version (8)?

I purchased this product, did the version on git is the full version?

Thank you

**Comment by eugentudorache** [comment]
Hello,

We're going to update to the latest version in the next days.

All the best


--
Eugen Tudorache Technical Director & Co-Founder m: +40 733 926 398 e: eugen@updivision.com [mailto:eugen@updivision.com] w: www.updivision.com [http://www.updivision.com/]
25 C.A. Rosetti St, 2nd floor, apt. 9
2nd District, Bucharest, Romania
On 11/09/2020 11:35:52, kenytux <notifications@github.com> wrote:
Hello,
Does the template support the last version (8)?
I purchased this product, did the version on git is the full version?
Thank you

**Comment by kenytux** [comment]
Hello,

Thank you.

I purchased this product, did the version on git is the full version?

Regards

**Comment by eugentudorache** [comment]
The PRO version is not on GIT, it's only available for download after purchase.


--
Eugen Tudorache Technical Director & Co-Founder m: +40 733 926 398 e: eugen@updivision.com [mailto:eugen@updivision.com] w: www.updivision.com [http://www.updivision.com/]
25 C.A. Rosetti St, 2nd floor, apt. 9
2nd District, Bucharest, Romania
On 11/09/2020 14:17:01, kenytux <notifications@github.com> wrote:
Hello,
Thank you.
I purchased this product, did the version on git is the full version?
Regards

**Comment by kenytux** [comment]
Thank You

**Comment by kenytux** [comment]
Can you give me a date for the update?

**Comment by eugentudorache** [comment]
Sure thing, I will follow up when it's done.
It should be middle of next week.

Best
Eugen


--
Eugen Tudorache Technical Director & Co-Founder m: +40 733 926 398 e: eugen@updivision.com [mailto:eugen@updivision.com] w: www.updivision.com [http://www.updivision.com/]
25 C.A. Rosetti St, 2nd floor, apt. 9
2nd District, Bucharest, Romania
On 11/09/2020 14:58:14, kenytux <notifications@github.com> wrote:
Can you give me a date for the update?

**Comment by teamupdivision** [comment]
Hi @kenytux 

We released a version for Laravel 8.x

All the best

**Comment by kenytux** [comment]
Hi @teamupdivision 

My download link is only for 1.0.2 version.

How do I get the 1.0.3 version download link?

Thank you
Best Regards

**Comment by teamupdivision** [comment]
Can you try again? We fixed the problem

**Comment by kenytux** [comment]
It's fixed!
Thank you
Best Regards
