### ISSUE TITLE
css issue

### ISSUE THREAD

**Issue by takujitsujikawa** [creativetimofficial/ct-paper-dashboard-pro-laravel#3]
Delete button is not displayed only at the bottom of the table.

![issue](https://user-images.githubusercontent.com/60605259/117113947-28870800-adc6-11eb-9787-8530e5fd275d.png)

**Comment by teamupdivision** [comment]
Hi @takujitsujikawa,

Thanks for reporting this issue and for using Creative Tim products.

We've pushed a fix to this problem.
You can access it by downloading the product from the downloads section on the Creative Tim website.
Please let us know if everything works ok and if there is any other issue. 

All the best,
UPDIVISION Team

**Comment by teamupdivision** [comment]
Hi there @takujitsujikawa, 

We would like to check if the issue was solved and if there is anything else we can help with. 
Please let us know if you have any other issues. 

All the best,
Updivision Team

**Comment by teamupdivision** [comment]
Hi @takujitsujikawa,
 
Hope this solved the problem. We will go ahead and close this ticket. If there is anything else that can be fixed or we can help with, please let us know.

Best,
UPDIVISION Team

P.S. If you need help with any of your projects, we're happy to get in touch. We do custom development for start-ups and companies across the globe (you can check out our portfolio here https://updivision.com/portfolio and some happy clients over here https://updivision.com/testimonials). Don`t hesitate to drop us a line at office@updivision.com or by using our contact form (https://updivision.com/contact).
