### ISSUE TITLE
Need VueJS version of this please.

### ISSUE THREAD

**Issue by shah-newaz** [creativetimofficial/ct-paper-dashboard-pro-laravel#4]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior
I expected to see a vuejs version of this when I purchased.

# Current Behavior
No VueJS version

**Comment by shah-newaz** [comment]
My bad! I found it. Thank you! Confusing because it's showing as a completely different product.

**Comment by teamupdivision** [comment]
Hi @shah-newaz 
 
Thank you for the update. If there is anything else we can help with, please let us know.

Best,
UPDIVISION Team

P.S. If you need help with any of your projects, we're happy to get in touch. We do custom development for start-ups and companies across the globe (you can check out our portfolio here https://updivision.com/portfolio and some happy clients over here https://updivision.com/testimonials). Don`t hesitate to drop us a line at office@updivision.com or by using our contact form (https://updivision.com/contact).
