### ISSUE TITLE
Photo profile and files not showing

### ISSUE THREAD

**Issue by luisfernandcys** [creativetimofficial/ct-paper-dashboard-pro-laravel#5]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [ x] I am running the latest version
- [ x] I checked the documentation and found no answer
- [ x] I checked to make sure that this issue has not already been filed
- [ x] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

Show picture

# Current Behavior

Picture uploaded but doesn't show correctly

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1.  i copied the full code
2. i started another project with the copied code
3. everything works fine except the photo and files (i can upload correctly but i can´t see it)

**Comment by teamupdivision** [comment]
Hi Luis,

Appreciate your use of Creative TIM products!

We've addressed your question via email. Moving forward, kindly utilize a single channel for reporting issues.

Thanks you!
